# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.6.8"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.8/lazyjira_darwin_amd64.tar.gz"
      sha256 "2b7117812e30a919fb676b859a836fac2df10c89adcee7db8596305826bfb9d6"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.8/lazyjira_darwin_arm64.tar.gz"
      sha256 "57c9c05aca773a8e08788d252116a12aefe17dfd80ab8062ede3cf7eb6a94d23"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.8/lazyjira_linux_amd64.tar.gz"
      sha256 "e24c8c2c30376c2ce314539e9b0e0e1220cc00eb2a036b2eca36b86b1b7b48eb"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.6.8/lazyjira_linux_arm64.tar.gz"
      sha256 "1dd9d4e700d519282fee85ef07eaf3350ec3b8a3d60b492746b2a45572980818"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end
end
