# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjira" do
  name "lazyjira"
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.4.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjira"

  on_macos do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_amd64.tar.gz"
      sha256 "f6bd5b106c6c7c79aebedd71983c3b1e19cace0098dca3d4930a5649d4447d41"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_arm64.tar.gz"
      sha256 "9ef442311802bf68042e883292ec2d4a1423fb21f06f39f501bf6946865b211f"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_amd64.tar.gz"
      sha256 "d482d257389f8ea3d1dcca5eff3a7770eb7a05cb60db0d06d400fb56136196bd"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_arm64.tar.gz"
      sha256 "1bd6f81ac617fd12eac4ef0b6b22bf7943e264392126c2fca12a35fc0a6424c2"
    end
  end

  # No zap stanza required
end
