# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjira" do
  version "2.6.3"

  on_macos do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_amd64.tar.gz"
      sha256 "f3b4bcb9de77bdc61fd9e76e3a48eb3d9efc1da0d7361250716b4ee219b169fa"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_arm64.tar.gz"
      sha256 "4ebe94ede92429d0e8ff5d6a802b8b6d75ec091d0c5b77accf11c484eecef8eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_amd64.tar.gz"
      sha256 "e31ba2289f4482fcdc226b6d98948b323624e1822558ec4a706d74235daa5725"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_arm64.tar.gz"
      sha256 "c6ff5c6cd57ccfa023ba025341c388995db3f67b5f757cf7a6f2340a940863b2"
    end
  end

  name "lazyjira"
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjira"

  # No zap stanza required

end
