# This file was generated by GoReleaser. DO NOT EDIT.
cask "lazyjira" do
  name "lazyjira"
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.4.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "lazyjira"

  on_macos do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_amd64.tar.gz"
      sha256 "4094e6a209d0eb880f9f688ff786187b8499c97c888383e6f3de1059c0103d40"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_darwin_arm64.tar.gz"
      sha256 "aa688d91603b46e6a48972a916b60f3ed1c4986e461194b3e53132a6cfde347b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_amd64.tar.gz"
      sha256 "4fab7d13e8b9157feb1cf4cd211727c34ede82f1df139fb290cd1e70b65442b7"
    end
    on_arm do
      url "https://github.com/textfuel/lazyjira/releases/download/v#{version}/lazyjira_linux_arm64.tar.gz"
      sha256 "80d2871f9c3846e0e77b72c262da46b5c83a46ac2fee888549a4351379d512a1"
    end
  end

  # No zap stanza required
end
