# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.1.0/lazyjira_darwin_amd64.tar.gz"
      sha256 "a1bc864d52ccc11ae897a809a041218144d0cf577c1db54bf15ff6090fe8455b"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.1.0/lazyjira_darwin_arm64.tar.gz"
      sha256 "034f004ae767caaed1c89ecb3f8882ca539da31cc002248d26732c94f7e4e1af"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.1.0/lazyjira_linux_amd64.tar.gz"
      sha256 "c989c843c3cf6847bfed78e7d628e4815b06619016834b3b913fe73d8713581e"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.1.0/lazyjira_linux_arm64.tar.gz"
      sha256 "b10af6105cf61c072406aab6eef8277fc42b021605b55c05d6e9be38525ab79e"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  test do
    assert_match "lazyjira", shell_output("#{bin}/lazyjira --version")
  end
end
