# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazyjira < Formula
  desc "Terminal UI for Jira"
  homepage "https://github.com/textfuel/lazyjira"
  version "2.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.3.0/lazyjira_darwin_amd64.tar.gz"
      sha256 "6b8e7188c1980f28e9fee2cd0616344c7e3b6c41325bfaf194caf0ac9c90f041"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.3.0/lazyjira_darwin_arm64.tar.gz"
      sha256 "ab6f97ec3f6a01e810a3f10f02f64793207bcac0c3edd7b29f12f05c5a2ca476"

      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.3.0/lazyjira_linux_amd64.tar.gz"
      sha256 "6bb8240ced0821faad8c0a8788eb5a5f3ebf060c78be6c342cdd5942f00c4f03"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/textfuel/lazyjira/releases/download/v2.3.0/lazyjira_linux_arm64.tar.gz"
      sha256 "80a25308f50858818e679cf43cc7898282f4fd52b9fb2e971d67b329d102193a"
      define_method(:install) do
        bin.install "lazyjira"
      end
    end
  end

  test do
    assert_match "lazyjira", shell_output("#{bin}/lazyjira --version")
  end
end
